### ISSUE TITLE
Maintaining Puppetboard - looking for volunteers

### ISSUE THREAD

**Issue by daenney** [puppet-community/puppetboard#132]
Though it pains me to write this I am no longer able to maintain Puppetboard.

I have commitments to many open source projects which at this point means I am spread to thin. Paired with no longer having a need to develop this project on a personal or professional basis it has slipped further and further. This is harmful to the project and its continuity.

There are however plenty of people and organisations that rely on this project. As such I am hoping that some will step up and take over from me. I'm more than happy to facilitate discussions or function in an advisory capacity but I can no longer be the driver.

If you'd like to take over I'd like to know a few things:

* Why you want to take over / will be able to work on it
* What your PyPi username is so I can give you upload privileges

I have only one constraint. Puppetboard resides in the Puppet-Community Github organisation and I expect it to stay there. It's a project that was started by Puppet community members and that was contributed to by Puppet community members. As such it belongs here.

**Comment by daenney** [comment]
This relates to puppet-community/pypuppetdb#50.

**Comment by ruckc** [comment]
I may be able to take this over.  Currently evaluating for replacing Puppet Dashboard, if it all works out, taking it over shouldn't be an issue.

**Comment by daenney** [comment]
Thank you, that would be great.

**Comment by gotyaoi** [comment]
We use this project at work, so I might be able to help out a bit, if I could wrangle some time. Even on my own though, I'd like to help, but it would be pretty much evening and weekends in that case...

**Comment by stack72** [comment]
@daenney you should speak to @liamjbennett and @amwilson to see if they can help as they use it at OpenTable. @amwilson has been modifying it already

**Comment by daenney** [comment]
Thanks @stack72, I'll reach out to them

**Comment by nibalizer** [comment]
I am happy to help, but I can only maintain/merge prs. Not drive the direction of the project.

**Comment by nibalizer** [comment]
@daenney can you clarify if you mean the above to apply to pypuppetdb as well or just puppetboard?

**Comment by daenney** [comment]
@nibalizer I've raised a similar issue on pypuppetdb's repo so yeah, both.

**Comment by ruckc** [comment]
After looking at this indepth, I can't maintain this in its current form.  My systems work on a non-internet connected network, and trying to just get dependencies installed has made this unmanageable for my organization.

**Comment by daenney** [comment]
How do you install any piece of software in that case? Do you run full mirrors of everything?

**Comment by ruckc** [comment]
For example, rubygems are easy standup a mirror, and gem will let you point to that, or you can gem2rpm, and manage it with yum.

Python's closest attempt (that i could find) is py2pack, which i couldn't get working at all, and required direct connection to the internet (no ability to specify the repository).

All said, i spent two days trying to turn puppetboard and dependencies into rpms easily (not generating the .spec by hand) and i've failed.

**Comment by daenney** [comment]
If you want to set up a pypi mirror use [devpi](http://doc.devpi.net/latest/) which can mirror+proxy to upstream. Simply point pip to it through the index url settings.

Then there's [fpm](https://github.com/jordansissel/fpm) and [`python setup.py bdist_rpm`](https://docs.python.org/2/distutils/builtdist.html#creating-rpm-packages) which should generate an RPM for you based on the project's `setup.py`.

**Comment by fgimian** [comment]
I'm happy to make contributions to the project and assist where I can.  I already have quite a few improvements in my own local checkout of the repo that I'll be sending through soon.

I would really like to have 2 - 3 people contributing though as I can't dedicate a lot of time to the project te become the sole maintainer.

Cheers
Fotis

**Comment by daenney** [comment]
Alright. So if we can get a few people to "actively" contribute to the project I don't mind keeping tabs on it and working with you to merge code base changes. I can grant a few people committer access.

**Comment by stack72** [comment]
@daenney I have it all checked out and working locally. I don't have time to contribute code to it, but i can certainly help merge PRs etc if you want?

**Comment by fgimian** [comment]
P.S.: Auto-refresh would be high on my priority list too for the Overview screen.  We've used Angular.js to do stuff like that at work and it works great, but I'd love to avoid it if possible.

I'll submit some pull requests soon!

To be honest, I think that Puppetboard is an awesome dashboard which is really simply and well designed.  PanoPuppet is also great but I can't help wonder why the author didn't contribute to Puppetboard instead of starting a new project.

Ultimately, I'd like to take what's good about PanoPuppet and implement it in Puppetboard if I can.  Puppetboard already meets most our requirements, but would be great to have the features I mentioned above.

Cheers
Fotis

**Comment by daenney** [comment]
@fgimian Yeah, I've seen PanoPuppet, I was a bit like "wtf mate" but you know, FOSS :smile:

@stack72 That would be helpful. I basically don't have the time to do feature development on it, so as a consequence I've become sort of a blocker on most of the PRs etc. That's mostly what I'm looking to resolve.

**Comment by stack72** [comment]
@daenney perfect - I can get started asap :)

**Comment by fgimian** [comment]
@daenney Okies, I've submitted a half dozen pull requests for you today, hehe :smile:  Please let me know if you would consider giving me push privileges to the main repo so I can contribute directly.

**Comment by daenney** [comment]
@fgimian I've given you committer access to Puppetboard and pypuppetdb. I'd still appreciate it if you raise PRs for bigger changes so that others have a chance to review and comment on it.

Feel free to go through the currently pending PRs, close what you deem no longer necessary and try to revive/redo some of the other feature requests.

**Comment by fgimian** [comment]
Sure, thank you so much :smile:

**Comment by fgimian** [comment]
I'm afraid the permissions don't appear to work mate, I'm getting a 403 when attempting to push and I can't seem to close issues and merge PRs.  Any ideas?

**Comment by daenney** [comment]
@fgimian It helps if you actually accept the invite that Github sent you :stuck_out_tongue_closed_eyes:.

**Comment by fgimian** [comment]
Oooooopsss!!! I'm so sorry, hehe! :smile:

**Comment by daenney** [comment]
There you go. Now you have the collaborator badge. Good luck :smile:.

**Comment by daenney** [comment]
@fgimian Feel free to join #puppetboard on Freenode, makes talking a bit easier.

**Comment by propyless** [comment]
Hello dev of panopuppet here :)

We've tested puppetboard at work quite extensivly, we even use it at some sites. They only have like 200-500 nodes. But when the bigger sites have over 3000 nodes puppetboard starts to be really slow. Panopuppet has been tested in an env with 36000 nodes and still had response times around 3-5 seconds.

I wrote panopuppet mainly to have a home project since I have no on-going projects. I also have a hard time reading into other peoples code so I preferrred to write my own dashboard.
While puppetboard hadn't had so much activity for the past few months until recently it also motiviated me to write my own.
I also wanted to learn django since i've already used flask. It was more of an gaining experience project.

Hope you don't feel that i'm pulling one over you.

Regards,
Takeshi

**Comment by stack72** [comment]
@daenney *nudge* for the perms to help merge PRs etc ;)

**Comment by nibalizer** [comment]
@stack72 @fgimian have access. As do I. If other people find this and want to contribute let us know.

**Comment by corey-hammerton** [comment]
@nibalizer *nudge* for PyPi permissions for coreyhammerton to puppetboard and pypuppetdb.

**Comment by daenney** [comment]
Done, you have access now.

**Comment by nibalizer** [comment]
woot

**Comment by fgimian** [comment]
@daenney Hey mate, if you have found some more maintainers for this awesome project, then you may wish to remove me.  We now use Foreman (in the form of Red Hat Satellite) at work and therefore I must admit that I haven't really put any effort into this project since becoming an official committer.  You are welcome to remove me and I'll submit any new ideas as pull requests if I come back to Puppetboard in the future :smile:

**Comment by daenney** [comment]
@fgimian Noted :).

**Comment by daenney** [comment]
@corey-hammerton I really need you to start being available in at least #puppetboard on Freenode and preferably also #puppet-community. People need support sometimes when things go wrong but have no way of reaching the maintainer. That's not a good experience.

**Comment by corey-hammerton** [comment]
Done @daenney. That being said do you mind if I remove your name from the README and the footer in favour of "Puppet Community"? There's not much point in listing individuals since this is a part of the Puppet Community organization.

**Comment by nibalizer** [comment]
I'd be in favor of removing the whole bar, all it does it eat vertical space.
