### ISSUE TITLE
ENC support?

### ISSUE THREAD

**Issue by anarcat** [puppet-community/puppetboard#134]
since this is described as a "puppet-dashboard replacement", are there plans to also implement the ENC capabilities of puppet-dashboard here?

**Comment by daenney** [comment]
We don't state that it's a Puppet Dashboard replacement:

> Puppetboard is a web interface to PuppetDB aiming to replace the reporting functionality of Puppet Dashboard.

It's only aiming to replace the reporting part and it's solely based on PuppetDB. Since PuppetDB doesn't offer ENC capabilities, neither do we.

**Comment by anarcat** [comment]
understood, thanks!

**Comment by divad** [comment]
Would you be opposed to me and my colleagues adding ENC functionality to PuppetBoard? Via a pull request at some point?

**Comment by nibalizer** [comment]
I think having a community web-enc is a good thing. I'm not sure I like the idea of bolting it on to puppetboard. We're behind on prs and features as it is. One concern I have is auth. Puppetboard is simple because it doesn't have an auth system.... if you can hit puppetboard then you can view puppet reports. Adding auth would seem to be a requirement for an ENC. There is a plugin effort in place on another PR(#168), that possibly could be leveraged to build out ENC functionality. 

Ideas:

1) Build an ENC into puppetboard
2) Break out common bits into a puppetweb-libs repository, and have puppetboard and puppetenc be separate flask apps that share a look and feel.
3) Build an ENC as a puppetboard-plugin (after the plugin system is complete)

**Comment by divad** [comment]
I think 3 is the best option in the short term.

I've commented on the issue regarding plugins as well - suggesting Flask Blueprints. 

Adding authentication to puppetboard should be very easy if we rely on LDAP, of course not everybody will have an LDAP directory to use. I'd be happy to work on adding auth if nobody else has done so? I think auth should be in the core in my opinion, starting with LDAP support. I've already got working LDAP/Flask authentication in several of UoS's (my employers) Flask apps.

**Comment by daenney** [comment]
I don't want to see custom auth/login/session code or anything hardcoded to any authentication backend. That's a recipe for disaster security wise and a problem later on extension wise. 

Things like Flask-Login can handle a myriad of authentication providers, from LDAP through Basic/Digest and oauth and integrate well with other packages providing authorisation like Flask-Principal.
